name: deploy to lambda
on:
  push:
    branches:
      - main
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: pnpm install
        run: |
          pnpm install

      - name: Run tests
        run: npm run test

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Bundle
        run: npm run bundle

      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: monthlyControl
          zip_file: bundle.zip
